# Generated by Django 3.2.8 on 2021-10-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211009_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtrating',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
