# Generated by Django 3.2.8 on 2021-10-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_produtrating_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutRating',
            new_name='ProductRating',
        ),
    ]
