# Generated by Django 3.2.8 on 2021-10-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_produtrating_productrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
