# Generated by Django 3.2.8 on 2021-10-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_sub_category', '0003_alter_subcategory_category'),
        ('product', '0007_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_from', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_sub_category.subcategory')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail_set', to='product.product')),
                ('product_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_from_set', to='product.productfrom')),
            ],
        ),
    ]
