# Generated by Django 3.2.8 on 2021-10-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20211015_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
