# Generated by Django 3.2.8 on 2021-10-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productdetail_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='category',
            new_name='sub_category',
        ),
    ]
