# Generated by Django 3.2.8 on 2021-10-21 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0001_initial'),
        ('product', '0010_rename_category_productdetail_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_category.category'),
            preserve_default=False,
        ),
    ]
