# Generated by Django 3.2.8 on 2021-10-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0001_initial'),
        ('product', '0011_auto_20211021_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_category.category'),
            preserve_default=False,
        ),
    ]
