# Generated by Django 3.2.8 on 2021-10-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20211024_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='date',
        ),
    ]
