# Generated by Django 3.2.8 on 2021-10-17 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_review', '0004_alter_like_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_review',
        ),
        migrations.AddField(
            model_name='review',
            name='sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_review_set', to='user.user'),
            preserve_default=False,
        ),
    ]
