# Generated by Django 3.2.8 on 2021-10-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_review', '0006_alter_review_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='sender',
            new_name='user',
        ),
    ]
