# Generated by Django 3.2.8 on 2021-10-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='id',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user'),
            preserve_default=False,
        ),
    ]
