# Generated by Django 3.2.8 on 2021-10-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='date_birth',
            field=models.DateField(null=True),
        ),
    ]
