# Generated by Django 3.2.8 on 2021-10-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_personalinformation_date_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='PersonalInformation',
        ),
    ]
